[package]
org = "flavianosilva"
name = "cidadao"
version = "0.1.0"
distribution = "2201.8.6"

[[platform.java17.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"
path = "../libs/postgresql-42.7.2.jar"

[build-options]
observabilityIncluded = true
